from os import environ

CONSUMER_KEY = environ['CONSUMER_KEY']
CONSUMER_SECRET = environ['CONSUMER_SECRET']
ACCESS_KEY = environ['ACESS_KEY']
ACCESS_SECRET = environ['ACCESS_SECRET']
JAWSDB_URL = environ['JAWSDB_URL']